fieldLayouts:
  1937a214-1ec4-4b42-be75-86046b57e746:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 75
          -
            fieldUid: 1eecdd2c-f9c5-4379-b304-d81774f9391e # Increase Title Contrast
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 55c8d23d-ad74-43a2-a3f2-8c4b6d969fe2 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f6ff43e3-8e77-457f-91cb-101f517889c9 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
      -
        elements:
          -
            fieldUid: bff42a0d-5c92-4f22-9957-9363f0a62656 # Related articles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Articles
        sortOrder: 2
      -
        elements:
          -
            fieldUid: e62d63b0-c299-42ce-aeef-86a69f7e676c # Seo Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: default
hasTitleField: true
name: Standard
section: a3a00a5e-73ba-4e8a-9800-375c9be802a9 # Topic
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
